WorldDomination_draft2/Models/ListOfPlans.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WorldDomination_draft2.Models
{
    public class ListOfPlans
    {
        public List<Plan> plans { get;set; }
    }
}

WorldDomination_draft2/Models/Plan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WorldDomination_draft2.Models
{
    public class Plan
    {
        public int planId { get; set; }
        public string name { get; set; }
        public string country { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-mm-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? date { get; set; } //date picker

        [Display(Name="Method")]
        public string takeoverMethod { get; set; } //dropdown

        public IEnumerable<SelectListItem> takeoverMethodList
        {
            get
            {
                List<SelectListItem> methodList = new List<SelectListItem>();
                methodList.Add(new SelectListItem { Text = "space lasers", Value = "space lasers" });
                methodList.Add(new SelectListItem { Text = "earhtquake", Value = "earhtquake" }); 
                methodList.Add(new SelectListItem { Text = "weather control device", Value = "weather control device" }); 
                methodList.Add(new SelectListItem { Text = "giant robot", Value = "giant robot" });

                return methodList;
            }
        }

        //constructor
        public Plan (int id, string name, string country, DateTime date, string method)
        {
            this.planId = id;
            this.name = name;
            this.country = country;
            this.date = date;
            this.takeoverMethod = method;
        }

        //constructor
        public Plan()
        {
            this.planId = 0;
            this.name = "";
            this.country = "";
            this.date = null;
            this.takeoverMethod = "";
        }



    }
}

WorldDomination_draft2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorldDomination_draft2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WorldDomination_draft2/Controllers/WorldDominationController.cs
using WorldDomination_draft2.Models;
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Web.Routing;
//using System.Windows.Forms;


namespace WorldDomination_draft2.Controllers
{
    public class WorldDominationController : Controller
    {
        // GET: WorldDomination
        public ActionResult CreatePlan()
        {
            Plan model = new Plan();
            
            return View(model);
        }

        [HttpPost]
        public ActionResult CreatePlan(Plan plan)
        {
           if(ModelState.IsValid)
            {
                //send to PleanDetails' view
                return RedirectToAction("MyPlanDetails", new { planId=plan.planId, name=plan.name, country= plan.country, date=plan.date,  method = plan.takeoverMethod });
            }
                return View();
            
        }

        

        public ActionResult MyPlanDetails(int planId, string name, string country, DateTime date, string method)
        {
            Plan model = new Plan(planId, name, country, date, method);

            return View(model);
        }


        public ActionResult ListPlans()
        {
            List<Plan> MyPlans = new List<Plan>();
            MyPlans.Add(new Plan(1, "My First Takeover", "Canada", Convert.ToDateTime("2019-01-01"), "polar bear army"));
            MyPlans.Add(new Plan(2, "To the South!", "USA", Convert.ToDateTime("2019-02-12"), "meteror shower"));
            MyPlans.Add(new Plan(3, "Le Mwahahaha!!", "France", Convert.ToDateTime("2019-05-02"), "cheese embargo"));
            MyPlans.Add(new Plan(4, "The stealth plan", "Russia", Convert.ToDateTime("2019-06-21"), "ant invasion"));

            ListOfPlans plans = new ListOfPlans();
            plans.plans = MyPlans;

            return View(plans);
        }
 


    }
}

WorldDomination_draft2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WorldDomination_draft2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WorldDomination_draft2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WorldDomination_draft2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WorldDomination_draft2/Views/WorldDomination/CreatePlan.cshtml
@model WorldDomination_draft2.Models.Plan
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create a new Plan</title>
</head>
<body>
    <div>

        <h1>Mwahahahahaha!!!</h1>
        <h2>Next Takeover</h2>
        <h3>Select plan details...</h3>

        @using (Html.BeginForm("CreatePlan", "WorldDomination", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-sm-2">
                    @Html.LabelFor(model => model.planId, new { style = "float:right;" })
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.planId)
                </div>
            </div><br />

            <div class="row">
                <div class="col-sm-2">
                    @Html.LabelFor(model => model.name, new { style = "float:right;" })
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.name)
                </div>
            </div><br />

            <div class="row">
                <div class="col-sm-2">
                    @Html.LabelFor(model => model.country, new { style = "float:right;" })
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.country)
                </div>
            </div><br />

            <div class="row">
                <div class="col-sm-2">
                    @Html.LabelFor(model => model.date, new { style = "float:right;" })
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.date)
                </div>
            </div><br />

            <div class="row">
                <div class="col-sm-2">
                    @Html.LabelFor(model => model.takeoverMethod, new { style = "float:right;" })
                </div>
                <div class="col-sm-8">
                    @Html.DropDownListFor(model => model.takeoverMethod, Model.takeoverMethodList)
                </div>
            </div><br />



            <br />
            <input type="submit" value="Save Plan!" id="btnSubmit" />

        }

    </div>


</body>
</html>

WorldDomination_draft2/Views/WorldDomination/ListPlans.cshtml
@model WorldDomination_draft2.Models.ListOfPlans
@{
    ViewBag.Title = "ListPlans";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Plans</h2>

<table class="table">
    <tr>
        <th>
            Plan ID
        </th>
        <th>
            Plan Name
        </th>
        <th>
            Country to Take Over
        </th>
        <th>
            Takeover Method
        </th>
        <th>
            Takeover Date
        </th>
    </tr>

 
   @foreach (var item in Model.plans )
    {


    <tr>
        <td>
            @Html.DisplayFor(model => item.planId)
        </td>
        <td>
            @Html.DisplayFor(model => item.name)
        </td>
        <td>
            @Html.DisplayFor(model => item.country)
        </td>
        <td>
            @Html.DisplayFor(model => item.takeoverMethod)
        </td>
        <td>
            @Html.DisplayFor(model => item.date)
        </td>
        <td>
            @Html.ActionLink("details", "PlanDetails")
        </td>
    </tr>
    }

</table>

WorldDomination_draft2/Views/WorldDomination/MyPlanDetails.cshtml
@model WorldDomination_draft2.Models.Plan
@{
    ViewBag.Title = "PlanDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Review Plan Details</h2>

<div class="row">
    <div class="col-sm-2">
        @Html.LabelFor(model => model.name, new { style = "float:right;" })
    </div>
    <div class="col-sm-8">
        @Html.DisplayFor(model => model.name)
    </div>
</div><br />

<div class="row">
    <div class="col-sm-2">
        @Html.LabelFor(model => model.country, new { style = "float:right;" })
    </div>
    <div class="col-sm-8">
        @Html.DisplayFor(model => model.country)
    </div>
</div><br />

<div class="row">
    <div class="col-sm-2">
        @Html.LabelFor(model => model.date, new { style = "float:right;" })
    </div>
    <div class="col-sm-8">
        @Html.DisplayFor(model => model.date)
    </div>
</div><br />

<div class="row">
    <div class="col-sm-2">
        @Html.LabelFor(model => model.takeoverMethod, new { style = "float:right;" })
    </div>
    <div class="col-sm-8">
        @Html.DisplayFor(model => model.takeoverMethod)
    </div>
</div><br />



<br />
@Html.ActionLink("Back to List", "ListPlans")